/**
 * The redaction boundary (Doc 10 §8).
 *
 * Two things are being asserted, and the second is the one that matters:
 *
 * 1. **The denylist works.** Fields named after what they hold are stripped.
 *    Easy, and not much of a defence on its own.
 * 2. **The shape check works.** A secret reaches `payload` under an innocuous
 *    name — spread from an input object, nested inside a `before`/`after` diff,
 *    tucked in an array — and is still stripped. That is the case a denylist
 *    cannot cover and the one that actually happens.
 *
 * The over-redaction cases are here for the same reason: an audit row that
 * cannot say which account was created is not useful, so `account_key`, uuids
 * and dotted permission keys must survive intact. Every real value below is
 * generated by the same function that mints the real thing, so the test cannot
 * drift from the format it is defending against.
 */

import { randomUUID } from 'node:crypto';
import {
  CIRCULAR,
  REDACTED,
  TRUNCATED,
  isSecretKey,
  looksLikeSecret,
  redactPayload,
} from './redact';
import {
  formatRefreshToken,
  mintRefreshSecret,
  hashRefreshSecret,
} from '../auth/refresh-token.util';
import {
  mintAccountKey,
  mintAccountSecret,
} from '../auth/service-credentials.util';

describe('isSecretKey', () => {
  it.each([
    'password',
    'newPassword',
    'password_confirmation',
    'passwd',
    'secret',
    'account_secret',
    'clientSecret',
    'token',
    'refresh_token',
    'previousRefreshTokenHash',
    'hash',
    'key_hash',
    'KEY-HASH',
    'secretHash',
    'salt',
    'credential',
    'apiKey',
    'privateKey',
    'signature',
    'authorization',
    'Cookie',
  ])('denies %s', (key) => {
    expect(isSecretKey(key)).toBe(true);
  });

  it.each([
    // The public half of a service-account credential, audited on purpose.
    'account_key',
    'key',
    'name',
    'email',
    'client_id',
    'reason',
    'device_label',
    'status',
    'permission',
    'sort_order',
  ])('allows %s', (key) => {
    expect(isSecretKey(key)).toBe(false);
  });
});

describe('looksLikeSecret', () => {
  it('catches an argon2id hash', () => {
    expect(looksLikeSecret('$argon2id$v=19$m=19456,t=2,p=1$c29tZXNhbHQ$aGFzaA')).toBe(
      true,
    );
  });

  it('catches a bcrypt hash', () => {
    expect(looksLikeSecret('$2b$12$abcdefghijklmnopqrstuv')).toBe(true);
  });

  it('catches a JWT', () => {
    const jwt =
      'eyJhbGciOiJSUzI1NiIsImtpZCI6ImsxIn0.eyJzdWIiOiJ1MSJ9.c2lnbmF0dXJl';
    expect(looksLikeSecret(jwt)).toBe(true);
  });

  it('catches a refresh token in this system’s own format', () => {
    expect(looksLikeSecret(formatRefreshToken(randomUUID(), mintRefreshSecret()))).toBe(
      true,
    );
  });

  it('catches a bare refresh secret and its stored hash', () => {
    const secret = mintRefreshSecret();
    expect(looksLikeSecret(secret)).toBe(true);
    expect(looksLikeSecret(hashRefreshSecret(secret))).toBe(true);
  });

  it('catches a service-account secret', () => {
    expect(looksLikeSecret(mintAccountSecret())).toBe(true);
  });

  it('catches a hex digest', () => {
    expect(looksLikeSecret('a'.repeat(64))).toBe(true);
  });

  it('spares a service-account key — it is the public half', () => {
    expect(looksLikeSecret(mintAccountKey())).toBe(false);
  });

  it('spares a uuid', () => {
    expect(looksLikeSecret(randomUUID())).toBe(false);
  });

  it('spares a dotted permission key, which denials must record', () => {
    expect(looksLikeSecret('gatepass.dc.approve')).toBe(false);
    expect(looksLikeSecret('iam.platform.application.create')).toBe(false);
  });

  it('spares ordinary values', () => {
    for (const value of [
      'Gate-3 Terminal',
      'operator@example.com',
      'acme-manufacturing',
      'n_4f3a2b1c.n_9d8e7f6a',
      'failed_attempts',
    ]) {
      expect(looksLikeSecret(value)).toBe(false);
    }
  });
});

describe('redactPayload', () => {
  it('strips denied keys whatever the value is', () => {
    expect(
      redactPayload({ password: 'short', key_hash: 42, token: null }),
    ).toEqual({ password: REDACTED, key_hash: REDACTED, token: REDACTED });
  });

  it('strips a secret that arrives under an innocuous name', () => {
    // The failure this whole file exists for: `{ ...input }` carrying a
    // credential into a field the denylist has never heard of.
    const redacted = redactPayload({ value: mintAccountSecret() });
    expect(redacted['value']).toBe(REDACTED);
  });

  it('recurses into nested objects and arrays', () => {
    const secret = mintAccountSecret();
    const redacted = redactPayload({
      before: { name: 'gatepass-bot', account_key: 'sa_abc' },
      after: { name: 'gatepass-bot', nested: { leaked: secret } },
      candidates: [{ leaked: secret }, 'Gate-3'],
    });

    expect(redacted).toEqual({
      before: { name: 'gatepass-bot', account_key: 'sa_abc' },
      after: { name: 'gatepass-bot', nested: { leaked: REDACTED } },
      candidates: [{ leaked: REDACTED }, 'Gate-3'],
    });
  });

  it('leaves an account_key intact, so the row names the account', () => {
    const key = mintAccountKey();
    expect(redactPayload({ account_key: key, name: 'gatepass-bot' })).toEqual({
      account_key: key,
      name: 'gatepass-bot',
    });
  });

  it('redacts raw bytes rather than encoding them', () => {
    expect(redactPayload({ blob: Buffer.from('key material') })).toEqual({
      blob: REDACTED,
    });
  });

  it('normalises non-JSON values the way jsonb needs them', () => {
    const when = new Date('2026-08-14T09:30:00.000Z');
    expect(
      redactPayload({
        when,
        count: 3n,
        missing: undefined,
        fn: () => undefined,
        empty: null,
      }),
    ).toEqual({ when: when.toISOString(), count: '3', empty: null });
  });

  it('keeps array indices stable when an element has no JSON form', () => {
    expect(redactPayload({ rows: [1, undefined, 2] })).toEqual({
      rows: [1, null, 2],
    });
  });

  it('stops at a cycle instead of recursing forever', () => {
    const node: Record<string, unknown> = { name: 'root' };
    node['self'] = node;

    expect(redactPayload({ node })).toEqual({
      node: { name: 'root', self: CIRCULAR },
    });
  });

  it('renders a value twice when it is shared between siblings, not once', () => {
    const shared = { name: 'shared' };
    expect(redactPayload({ a: shared, b: shared })).toEqual({
      a: { name: 'shared' },
      b: { name: 'shared' },
    });
  });

  it('truncates past the depth bound', () => {
    // Deeper than MAX_DEPTH (8): an audit payload is meant to be compact
    // (Doc 10 §2), and an unbounded walk is work a caller can provoke.
    let deep: Record<string, unknown> = { bottom: 'reached' };
    for (let i = 0; i < 12; i += 1) deep = { down: deep };

    expect(JSON.stringify(redactPayload(deep))).toContain(TRUNCATED);
  });
});
