/**
 * Client CRUD — tenant provisioning, step 1 (Doc 06 §5, Doc 02 §3).
 *
 * ## The one place a platform action writes a tenant row
 *
 * Every other platform surface writes catalog tables, which carry no `client_id`
 * and whose RLS policies gate on `app.is_platform_admin` alone (Doc 07 §6). This
 * one writes `client` itself, and the tenant policies of migration 0007 are
 * deliberately asymmetric: a platform admin *reads* across tenants, but every
 * `with check` pins writes to `app.current_client_id` with no platform arm, so
 * that a platform action cannot land a row under the wrong tenant.
 *
 * `client`'s own policy is the sharpest form of that — `with check (id =
 * app.current_client_id)` — which means creating a tenant requires the context to
 * already name the row being inserted. So the id is chosen first and
 * `withProvisioningTenant` points the context at it for the insert. That is not a
 * bypass: it is the "dedicated provisioning flow" Doc 07 §6 reserves for exactly
 * this, and it narrows what the transaction may write rather than widening it.
 * See `rls-context.ts` for the full argument, including why it does not violate
 * the provenance rule that `applyRlsContext` enforces.
 *
 * The same wrapper is why the audit rows land in the tenant they describe: the
 * `client.created` record for Acme is Acme's row, visible to Acme's admin under
 * Doc 10 §7's tenant read rule and to the platform admin who wrote it. Migration
 * 0011 does the same thing for the platform tenant's own bootstrap.
 *
 * ## There is no delete
 *
 * Doc 01 §3.4: tenants are suspended, never deleted. `PATCH` with
 * `status = 'suspended'` is the off switch, and Doc 06 §5 lists no `DELETE` —
 * every child table points at `client` with `on delete restrict` (migration
 * 0003), so the database would refuse one anyway, which is the intended answer
 * to "delete an organisation's entire access history".
 *
 * Suspension is enforced where it matters rather than here: migration 0012's
 * `auth_begin_session` re-checks `client.status` at the moment a session is
 * created, so a client suspended mid-flight gets no session even if the
 * credential check had already passed.
 *
 * ## Authorization
 *
 * `@RequirePermission('iam.platform.client.…')` on the routes, checked by
 * `PermissionGuard` before this service runs (Session 23). No scope target: a
 * platform grant is bound at the platform scope root, outside every customer
 * tree, and Doc 04 §10 has it skip the tenant coverage step. The `:id` in the
 * path is a *target*, not an authority — what may be done with it is decided by
 * a permission held at the platform root, never by the token's `cid`.
 */

import { Injectable } from '@nestjs/common';
import {
  ClientStatus,
  normalizePagination,
  paginated,
  type ClientDTO,
  type Paginated,
} from '@plantops/contracts';
import { IAM_SCHEMA, withProvisioningTenant } from '@plantops/db';
import { AUDIT_ACTIONS } from '../audit/audit-actions';
import { AuditService } from '../audit/audit.service';
import { entityManager } from '../common/transaction-context';
import { rethrowAsConflict } from '../registry/conflict';

const S = `"${IAM_SCHEMA}"`;

const COLUMNS = `id, name, slug, status, config, created_at, updated_at`;

/** The same columns, qualified — for the one query that joins another table. */
const C_COLUMNS = `c.id, c.name, c.slug, c.status, c.config, c.created_at, c.updated_at`;

/**
 * The Doc 09 §2.2 list column, as a correlated subquery rather than a join.
 *
 * Disabled rows are excluded on purpose: a `client_application` with
 * `enabled = false` is preserved, not active (Doc 02 §7), and counting it would
 * make the number mean "apps this tenant has ever been given" — which is not
 * what the column is for.
 */
const ENABLED_COUNT = `(
  select count(*)::int
    from ${S}."client_application" ca
   where ca.client_id = c.id and ca.enabled
)`;

export interface ClientRow {
  id: string;
  name: string;
  slug: string;
  status: ClientStatus;
  config: Record<string, unknown>;
  created_at: Date;
  updated_at: Date;
}

interface ClientListRow extends ClientRow {
  enabled_application_count: number;
}

export interface CreateClientInput {
  name: string;
  slug: string;
  config?: Record<string, unknown>;
}

export interface UpdateClientInput {
  name?: string;
  status?: ClientStatus;
  config?: Record<string, unknown>;
}

@Injectable()
export class ClientsService {
  constructor(private readonly audit: AuditService) {}

  /**
   * Creates a tenant (Doc 02 §3 step 1).
   *
   * The id is generated by the database *before* the insert rather than by its
   * own column default, because the RLS context has to name it first — see the
   * header. `gen_random_uuid()` rather than Node's `randomUUID()` for no reason
   * beyond keeping the value's provenance identical to every other row's.
   *
   * A duplicate slug is a 409 naming the slug. That is safe to say here in a way
   * it would not be on a tenant-facing endpoint: slugs are globally unique
   * because login carries one instead of a tenant id (Doc 03 §3), and the caller
   * is a platform admin who can list every client anyway.
   */
  async create(input: CreateClientInput): Promise<ClientDTO> {
    const manager = entityManager();
    const [{ id }] = (await manager.query(`select gen_random_uuid() as id`)) as {
      id: string;
    }[];

    return withProvisioningTenant(manager, id, async () => {
      let rows: ClientRow[];
      try {
        rows = (await manager.query(
          `insert into ${S}."client" (id, name, slug, config)
           values ($1, $2, $3, coalesce($4::jsonb, '{}'::jsonb))
           returning ${COLUMNS}`,
          [
            id,
            input.name,
            input.slug,
            input.config === undefined ? null : JSON.stringify(input.config),
          ],
        )) as ClientRow[];
      } catch (error) {
        rethrowAsConflict(error, `A client with the slug "${input.slug}" already exists`);
      }

      const row = rows[0];
      await this.audit.record(
        AUDIT_ACTIONS.CLIENT_CREATED,
        { type: 'client', id: row.id },
        { name: row.name, slug: row.slug },
      );

      // Nothing is enabled for a tenant that was created a statement ago.
      return toDto(row, 0);
    });
  }

  /**
   * Every tenant, alphabetically by name (Doc 06 §5).
   *
   * No context switch: this is a read, and the tenant policies' `using` arm
   * admits a platform admin across tenants (migration 0007). Ordered by name
   * rather than newest-first for the reason `ApplicationsService.list` is
   * ordered by key — an operator scans this list for an organisation they
   * already know.
   *
   * Suspended clients are included, and so is the `platform` tenant seeded by
   * migration 0011. Both are things that exist, and this is the only view of
   * what exists: filtering a suspended client out would leave no way to
   * reactivate it through the API, and hiding the platform row would misreport
   * what the `client` table contains to the one caller entitled to know.
   */
  async list(query: { page?: number; limit?: number } = {}): Promise<Paginated<ClientDTO>> {
    const { page, limit } = normalizePagination(query);

    const rows = (await entityManager().query(
      `select ${C_COLUMNS},
              ${ENABLED_COUNT} as enabled_application_count
         from ${S}."client" c
        order by c.name asc, c.id asc
        limit $1 offset $2`,
      [limit, (page - 1) * limit],
    )) as ClientListRow[];

    const [count] = (await entityManager().query(
      `select count(*)::int as total from ${S}."client"`,
    )) as { total: number }[];

    return paginated(
      rows.map((row) => toDto(row, row.enabled_application_count)),
      count?.total ?? rows.length,
      query,
    );
  }

  /**
   * Updates a tenant, or suspends / reactivates it (Doc 06 §5).
   *
   * Only genuinely changed fields reach the `update`, and a wholly no-op PATCH
   * writes no audit record — `ApplicationsService.update`'s rule, for the same
   * reason: a trail that logs "updated" every time a form is re-submitted
   * unchanged is one nobody can read.
   *
   * Suspension is recorded as `client.suspended` rather than as another
   * `client.updated`, because Doc 10 §4 gives it its own action and it is the one
   * edit here that locks an organisation out. Reactivation has no dedicated
   * action, so it rides in `client.updated` with `status` among the changed
   * fields.
   *
   * Returns `null` when no such client exists.
   */
  async update(id: string, input: UpdateClientInput): Promise<ClientDTO | null> {
    const manager = entityManager();

    return withProvisioningTenant(manager, id, async () => {
      const [current] = (await manager.query(
        `select ${COLUMNS} from ${S}."client" where id = $1`,
        [id],
      )) as ClientRow[];

      if (current === undefined) return null;

      const assignments: string[] = [];
      const parameters: unknown[] = [id];
      const changed: string[] = [];

      const assign = (column: string, value: unknown, cast = ''): void => {
        parameters.push(value);
        assignments.push(`${column} = $${parameters.length}${cast}`);
        changed.push(column);
      };

      if (input.name !== undefined && input.name !== current.name) {
        assign('name', input.name);
      }
      if (input.status !== undefined && input.status !== current.status) {
        assign('status', input.status, `::${S}."client_status"`);
      }
      if (
        input.config !== undefined &&
        JSON.stringify(input.config) !== JSON.stringify(current.config)
      ) {
        assign('config', JSON.stringify(input.config), '::jsonb');
      }

      if (assignments.length === 0) return toDto(current, await this.enabledCount(id));

      // Wrapped in a CTE so the statement's command is SELECT: TypeORM's
      // Postgres driver returns `[rows, rowCount]` for a bare
      // `update … returning`, and the destructuring below would read the count
      // as a row. Same reason `ApplicationsService.update` does it.
      const [row] = (await manager.query(
        `with updated as (
           update ${S}."client"
              set ${assignments.join(', ')}
            where id = $1
           returning ${COLUMNS}
         )
         select ${COLUMNS} from updated`,
        parameters,
      )) as ClientRow[];

      const suspended =
        current.status === ClientStatus.ACTIVE && input.status === ClientStatus.SUSPENDED;
      const otherChanges = changed.filter((column) => column !== 'status');

      if (otherChanges.length > 0 || !suspended) {
        await this.audit.record(
          AUDIT_ACTIONS.CLIENT_UPDATED,
          { type: 'client', id: row.id },
          {
            slug: row.slug,
            changed,
            // A compact before/after (Doc 10 §2) of the fields that moved.
            // `config` is named but never quoted: it is an opaque per-tenant
            // blob whose size this API does not bound, and a trail that pastes
            // one in on every edit stops being scannable.
            before: summarize(current, otherChanges),
            after: summarize(row, otherChanges),
          },
        );
      }

      if (suspended) {
        await this.audit.record(
          AUDIT_ACTIONS.CLIENT_SUSPENDED,
          { type: 'client', id: row.id },
          { name: row.name, slug: row.slug },
        );
      }

      return toDto(row, await this.enabledCount(id));
    });
  }

  /**
   * The client, or `null`.
   *
   * Not a route of its own — Doc 06 §5 has no `GET /iam/clients/:id` — but every
   * sub-resource needs it, because an application enabled for, or an admin
   * created under, an id that does not exist must be a 404 naming the client
   * rather than a foreign-key violation reported as a 500.
   *
   * Deliberately **not** gated: every caller is already past the route's own
   * `@RequirePermission`, and a second check here would be one more place for
   * the two to disagree.
   */
  async findRow(id: string): Promise<ClientRow | null> {
    const [row] = (await entityManager().query(
      `select ${COLUMNS} from ${S}."client" where id = $1`,
      [id],
    )) as ClientRow[];

    return row ?? null;
  }

  private async enabledCount(clientId: string): Promise<number> {
    const [row] = (await entityManager().query(
      `select count(*)::int as total
         from ${S}."client_application"
        where client_id = $1 and enabled`,
      [clientId],
    )) as { total: number }[];

    return row?.total ?? 0;
  }
}

/** The changed fields, by name, for a `before`/`after` payload. */
function summarize(row: ClientRow, columns: readonly string[]): Record<string, unknown> {
  const summary: Record<string, unknown> = {};
  for (const column of columns) {
    if (column === 'name') summary['name'] = row.name;
  }
  return summary;
}

export function toDto(row: ClientRow, enabledApplicationCount: number): ClientDTO {
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    status: row.status,
    config: row.config,
    enabled_application_count: enabledApplicationCount,
    created_at: row.created_at.toISOString(),
    updated_at: row.updated_at.toISOString(),
  };
}
